/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container": "#201f1f",
        "on-surface-variant": "#e9bcb6",
        "on-primary-container": "#fff7f6",
        "on-secondary": "#002e69",
        "surface": "#131313",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#004493",
        "secondary-fixed-dim": "#adc6ff",
        "on-error": "#690005",
        "outline-variant": "#5e3f3b",
        "on-tertiary-fixed-variant": "#004689",
        "secondary-fixed": "#d8e2ff",
        "on-surface": "#e5e2e1",
        "on-primary": "#690003",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#e50914",
        "secondary-container": "#4b8eff",
        "primary-fixed": "#ffdad5",
        "on-secondary-container": "#00285c",
        "surface-container-low": "#1c1b1b",
        "surface-dim": "#131313",
        "tertiary-container": "#0072d7",
        "background": "#131313",
        "secondary": "#adc6ff",
        "error-container": "#93000a",
        "surface-bright": "#3a3939",
        "outline": "#af8782",
        "primary-fixed-dim": "#ffb4aa",
        "on-primary-fixed": "#410001",
        "tertiary-fixed-dim": "#a7c8ff",
        "error": "#ffb4ab",
        "tertiary": "#a7c8ff",
        "primary": "#ffb4aa",
        "tertiary-fixed": "#d5e3ff",
        "on-tertiary-fixed": "#001b3c",
        "on-tertiary": "#003061",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "surface-tint": "#ffb4aa",
        "on-secondary-fixed": "#001a41",
        "surface-variant": "#353534",
        "inverse-primary": "#c0000c",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#f8f9ff",
        "on-primary-fixed-variant": "#930007"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "edge-margin-mobile": "20px",
        "container-max": "1440px",
        "section-gap": "80px",
        "gutter": "24px",
        "edge-margin-desktop": "64px",
        "row-gap": "40px"
      },
      "fontFamily": {
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "display-lg-mobile": ["40px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
